#!/usr/bin/env bash
#
# Generates THIRD_PARTY_NOTICES.txt: the licence text (and any NOTICE file) of
# every third-party module linked into the lstk binary, on every platform the
# release builds, plus the hand-written entries in extra/ for what go-licenses
# cannot see (modules without a licence file).
#
# The file is one superset for all platforms, so every release package carries
# an identical copy. It covers the Apache-2.0 lstk core only; the proprietary
# bundled extensions ship their own notices, generated by the same script in
# the private extensions repository (this is a port of it).
#
# Usage:
#   scripts/third-party-notices/generate.sh          # rewrite the file
#   scripts/third-party-notices/generate.sh --check  # fail if it is stale, or
#                                                    # if a dependency's licence
#                                                    # is not in ALLOWED_LICENSES
set -euo pipefail

GO_LICENSES_VERSION="v2.0.1"

# Licences a dependency may carry without review. Anything else, including a
# licence go-licenses cannot identify, fails --check.
ALLOWED_LICENSES="Apache-2.0,BSD-2-Clause,BSD-3-Clause,MIT,MPL-2.0,Unicode-DFS-2016"

# Kept in step with `builds` in .goreleaser.yaml.
PLATFORMS="linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64"

SELF_MODULE="github.com/localstack/lstk"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
EXTRA_DIR="${SCRIPT_DIR}/extra"
OUTPUT="${REPO_ROOT}/THIRD_PARTY_NOTICES.txt"

die() {
  echo "third-party-notices: $*" >&2
  exit 1
}

CHECK=0
case "${1-}" in
  "") ;;
  --check) CHECK=1 ;;
  *) die "unknown argument: $1" ;;
esac

WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

cd "${REPO_ROOT}"
MODCACHE="$(go env GOMODCACHE)"

# Modules covered by an extra/ entry are skipped by go-licenses: they are the
# ones it cannot classify.
IGNORES=(--ignore "${SELF_MODULE}")
for f in "${EXTRA_DIR}"/*.txt; do
  [ -f "${f}" ] || continue
  mod="$(sed -n 's/^Module: //p' "${f}")"
  [ -n "${mod}" ] && IGNORES+=(--ignore "${mod}")
done

GOBIN="${WORK}/bin" go install "github.com/google/go-licenses/v2@${GO_LICENSES_VERSION}"
GO_LICENSES="${WORK}/bin/go-licenses"

TAB="$(printf '\t')"
printf '{{range .}}{{.Name}}{{"\\t"}}{{.LicenseName}}{{"\\t"}}{{.LicensePath}}{{"\\t"}}{{.LicenseURL}}{{"\\n"}}{{end}}' \
  > "${WORK}/report.tmpl"

# The main package only, not ./...: test helpers under internal/ pull in
# modules the shipped binary never links. go-licenses prints klog warnings and
# assembly-file notes on stderr; those are dropped, real errors are shown.
for platform in ${PLATFORMS}; do
  goos="${platform%/*}"
  goarch="${platform#*/}"
  if [ "${CHECK}" -eq 1 ]; then
    GOOS="${goos}" GOARCH="${goarch}" "${GO_LICENSES}" check . \
      --allowed_licenses="${ALLOWED_LICENSES}" "${IGNORES[@]}" 2>"${WORK}/check.err" \
      || { grep -v -e '^W' -e '^/' "${WORK}/check.err" >&2 || true; die "${platform}: a dependency's licence is not in ALLOWED_LICENSES (see above)"; }
  fi
  GOOS="${goos}" GOARCH="${goarch}" "${GO_LICENSES}" report . \
    --template "${WORK}/report.tmpl" "${IGNORES[@]}" 2>"${WORK}/report.err" >> "${WORK}/raw.tsv" \
    || { grep -v -e '^W' -e '^/' "${WORK}/report.err" >&2 || true; die "${platform}: go-licenses report failed (see above)"; }
done

# One entry per licence file: packages of the same module share it, and a file
# holding two licences (e.g. MIT + Unicode) is reported once per licence.
# Output columns: module, version, licences (comma-joined), licence path, URL,
# module path as the module proxy escapes it.
awk -F"${TAB}" -v OFS="${TAB}" -v cache="${MODCACHE}/" '
  {
    path = $3
    if (index(path, cache) != 1) { print "licence outside the module cache: " path > "/dev/stderr"; exit 1 }
    rel = substr(path, length(cache) + 1)
    at = index(rel, "@")
    mod = substr(rel, 1, at - 1)
    esc = mod
    rest = substr(rel, at + 1)
    ver = substr(rest, 1, index(rest, "/") - 1)
    # The module cache escapes upper-case letters as "!" + lower-case.
    out = ""
    while (match(mod, /![a-z]/)) {
      out = out substr(mod, 1, RSTART - 1) toupper(substr(mod, RSTART + 1, 1))
      mod = substr(mod, RSTART + 2)
    }
    mod = out mod
    if (!(path in seen)) { seen[path] = 1; order[++n] = path; m[path] = mod; v[path] = ver; u[path] = $4; e[path] = esc }
    if (!((path, $2) in lic)) { lic[path, $2] = 1; l[path] = (l[path] == "" ? $2 : l[path] ", " $2) }
  }
  END { for (i = 1; i <= n; i++) { p = order[i]; print m[p], v[p], l[p], p, u[p], e[p] } }
' "${WORK}/raw.tsv" | LC_ALL=C sort -t"${TAB}" -k1,1 > "${WORK}/entries.tsv"

rule() { printf '%.0s=' $(seq 1 80); echo; }

emit_entry() { # name, licences, licence URL, source URL, text file, [notice file]
  rule
  echo "$1"
  echo "License: $2"
  [ -n "$3" ] && echo "License text: $3"
  echo "Source code: $4"
  rule
  echo
  cat "$5"
  if [ -n "${6-}" ]; then
    echo
    echo "--- NOTICE ---"
    echo
    cat "$6"
  fi
  echo
}

{
  cat <<'HEADER'
THIRD-PARTY SOFTWARE NOTICES

The lstk binary includes the third-party software listed below. Each
component is distributed under the licence reproduced with it. Its source
code, in the exact version included, is available at the "Source code"
address given.

This file covers the lstk core, which is licensed under Apache 2.0 (see
LICENSE). The bundled first-party extensions distributed alongside lstk are
proprietary and carry their own notices in
bundled-extensions.THIRD_PARTY_NOTICES.txt.

The list covers every platform the binary is built for; a component used on
only some platforms (for example Windows-only system bindings) is listed once.

This file is generated by scripts/third-party-notices/generate.sh. Do not edit
it by hand.

HEADER

  while IFS="${TAB}" read -r mod ver lics path url esc; do
    notice=""
    for n in "$(dirname "${path}")"/NOTICE*; do
      [ -f "${n}" ] && notice="${n}" && break
    done
    # The module proxy serves the exact source the binary was built from.
    emit_entry "${mod} ${ver}" "${lics}" "${url}" \
      "https://proxy.golang.org/${esc}/@v/${ver}.zip" "${path}" "${notice}"
  done < "${WORK}/entries.tsv"

  # The Go runtime and standard library are linked into every Go binary.
  emit_entry "Go standard library and runtime" "BSD-3-Clause" \
    "https://go.dev/LICENSE" "https://go.dev/dl/" "$(go env GOROOT)/LICENSE"

  for f in "${EXTRA_DIR}"/*.txt; do
    [ -f "${f}" ] || continue
    name="$(sed -n 's/^Name: //p' "${f}")"
    lics="$(sed -n 's/^License: //p' "${f}")"
    src="$(sed -n 's/^Source: //p' "${f}")"
    sed '1,/^---$/d' "${f}" > "${WORK}/extra-body"
    emit_entry "${name}" "${lics}" "" "${src}" "${WORK}/extra-body"
  done
} > "${WORK}/notices.txt"

# An extra/ entry for a Go module names the version it was written against;
# a dependency bump must revisit it.
for f in "${EXTRA_DIR}"/*.txt; do
  [ -f "${f}" ] || continue
  mod="$(sed -n 's/^Module: //p' "${f}")"
  [ -n "${mod}" ] || continue
  want="$(sed -n 's/^Name: .* //p' "${f}")"
  have="$(go list -m -f '{{.Version}}' "${mod}")"
  [ "${want}" = "${have}" ] || die "$(basename "${f}") describes ${mod} ${want}, but go.mod resolves ${have}; re-check its licence and update the entry"
done

# lstk embeds no third-party data (its only go:embed is its own default
# config), so unlike the extensions repository's copy of this script there is
# no embedded-file entry kind here.

if [ "${CHECK}" -eq 1 ]; then
  if ! diff -u "${OUTPUT}" "${WORK}/notices.txt" > "${WORK}/notices.diff"; then
    head -50 "${WORK}/notices.diff" >&2
    die "THIRD_PARTY_NOTICES.txt is stale; run scripts/third-party-notices/generate.sh and commit the result"
  fi
  echo "THIRD_PARTY_NOTICES.txt is up to date and every licence is allowed."
else
  cp "${WORK}/notices.txt" "${OUTPUT}"
  echo "Wrote ${OUTPUT} ($(grep -c '^License: ' "${OUTPUT}") components)."
fi
