// Code generated by MockGen. DO NOT EDIT.
// Source: diff.go
//
// Generated by this command:
//
//	mockgen -source=diff.go -destination=mock_diff_client_test.go -package=snapshot_test
//

// Package snapshot_test is a generated GoMock package.
package snapshot_test

import (
	context "context"
	reflect "reflect"

	snapshot "github.com/localstack/lstk/internal/snapshot"
	gomock "go.uber.org/mock/gomock"
)

// MockPodDiffer is a mock of PodDiffer interface.
type MockPodDiffer struct {
	ctrl     *gomock.Controller
	recorder *MockPodDifferMockRecorder
	isgomock struct{}
}

// MockPodDifferMockRecorder is the mock recorder for MockPodDiffer.
type MockPodDifferMockRecorder struct {
	mock *MockPodDiffer
}

// NewMockPodDiffer creates a new mock instance.
func NewMockPodDiffer(ctrl *gomock.Controller) *MockPodDiffer {
	mock := &MockPodDiffer{ctrl: ctrl}
	mock.recorder = &MockPodDifferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodDiffer) EXPECT() *MockPodDifferMockRecorder {
	return m.recorder
}

// DiffPodSnapshot mocks base method.
func (m *MockPodDiffer) DiffPodSnapshot(ctx context.Context, host, podName, authToken string) (snapshot.DiffResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiffPodSnapshot", ctx, host, podName, authToken)
	ret0, _ := ret[0].(snapshot.DiffResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiffPodSnapshot indicates an expected call of DiffPodSnapshot.
func (mr *MockPodDifferMockRecorder) DiffPodSnapshot(ctx, host, podName, authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiffPodSnapshot", reflect.TypeOf((*MockPodDiffer)(nil).DiffPodSnapshot), ctx, host, podName, authToken)
}
