// Code generated by MockGen. DO NOT EDIT.
// Source: save.go
//
// Generated by this command:
//
//	mockgen -source=save.go -destination=mock_state_exporter_test.go -package=snapshot_test
//

// Package snapshot_test is a generated GoMock package.
package snapshot_test

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStateExporter is a mock of StateExporter interface.
type MockStateExporter struct {
	ctrl     *gomock.Controller
	recorder *MockStateExporterMockRecorder
	isgomock struct{}
}

// MockStateExporterMockRecorder is the mock recorder for MockStateExporter.
type MockStateExporterMockRecorder struct {
	mock *MockStateExporter
}

// NewMockStateExporter creates a new mock instance.
func NewMockStateExporter(ctrl *gomock.Controller) *MockStateExporter {
	mock := &MockStateExporter{ctrl: ctrl}
	mock.recorder = &MockStateExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateExporter) EXPECT() *MockStateExporterMockRecorder {
	return m.recorder
}

// ExportState mocks base method.
func (m *MockStateExporter) ExportState(ctx context.Context, host string, dst io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportState", ctx, host, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportState indicates an expected call of ExportState.
func (mr *MockStateExporterMockRecorder) ExportState(ctx, host, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportState", reflect.TypeOf((*MockStateExporter)(nil).ExportState), ctx, host, dst)
}
