// Code generated by MockGen. DO NOT EDIT.
// Source: remote.go
//
// Generated by this command:
//
//	mockgen -source=remote.go -destination=mock_remote_client_test.go -package=snapshot_test
//

// Package snapshot_test is a generated GoMock package.
package snapshot_test

import (
	context "context"
	reflect "reflect"

	snapshot "github.com/localstack/lstk/internal/snapshot"
	gomock "go.uber.org/mock/gomock"
)

// MockRemoteClient is a mock of RemoteClient interface.
type MockRemoteClient struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteClientMockRecorder
	isgomock struct{}
}

// MockRemoteClientMockRecorder is the mock recorder for MockRemoteClient.
type MockRemoteClientMockRecorder struct {
	mock *MockRemoteClient
}

// NewMockRemoteClient creates a new mock instance.
func NewMockRemoteClient(ctrl *gomock.Controller) *MockRemoteClient {
	mock := &MockRemoteClient{ctrl: ctrl}
	mock.recorder = &MockRemoteClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteClient) EXPECT() *MockRemoteClientMockRecorder {
	return m.recorder
}

// ListPodsRemote mocks base method.
func (m *MockRemoteClient) ListPodsRemote(ctx context.Context, host, remoteName string, params map[string]string, authToken, creator string) ([]snapshot.RemotePod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPodsRemote", ctx, host, remoteName, params, authToken, creator)
	ret0, _ := ret[0].([]snapshot.RemotePod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPodsRemote indicates an expected call of ListPodsRemote.
func (mr *MockRemoteClientMockRecorder) ListPodsRemote(ctx, host, remoteName, params, authToken, creator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPodsRemote", reflect.TypeOf((*MockRemoteClient)(nil).ListPodsRemote), ctx, host, remoteName, params, authToken, creator)
}

// LoadPodRemote mocks base method.
func (m *MockRemoteClient) LoadPodRemote(ctx context.Context, host, podName, remoteName string, params map[string]string, authToken, strategy string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPodRemote", ctx, host, podName, remoteName, params, authToken, strategy)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPodRemote indicates an expected call of LoadPodRemote.
func (mr *MockRemoteClientMockRecorder) LoadPodRemote(ctx, host, podName, remoteName, params, authToken, strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPodRemote", reflect.TypeOf((*MockRemoteClient)(nil).LoadPodRemote), ctx, host, podName, remoteName, params, authToken, strategy)
}

// RegisterRemote mocks base method.
func (m *MockRemoteClient) RegisterRemote(ctx context.Context, host, name, remoteURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRemote", ctx, host, name, remoteURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterRemote indicates an expected call of RegisterRemote.
func (mr *MockRemoteClientMockRecorder) RegisterRemote(ctx, host, name, remoteURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRemote", reflect.TypeOf((*MockRemoteClient)(nil).RegisterRemote), ctx, host, name, remoteURL)
}

// S3BucketExists mocks base method.
func (m *MockRemoteClient) S3BucketExists(ctx context.Context, bucket string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "S3BucketExists", ctx, bucket)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// S3BucketExists indicates an expected call of S3BucketExists.
func (mr *MockRemoteClientMockRecorder) S3BucketExists(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "S3BucketExists", reflect.TypeOf((*MockRemoteClient)(nil).S3BucketExists), ctx, bucket)
}

// SavePodRemote mocks base method.
func (m *MockRemoteClient) SavePodRemote(ctx context.Context, host, podName, remoteName string, params map[string]string, authToken string) (snapshot.PodSaveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePodRemote", ctx, host, podName, remoteName, params, authToken)
	ret0, _ := ret[0].(snapshot.PodSaveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePodRemote indicates an expected call of SavePodRemote.
func (mr *MockRemoteClientMockRecorder) SavePodRemote(ctx, host, podName, remoteName, params, authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePodRemote", reflect.TypeOf((*MockRemoteClient)(nil).SavePodRemote), ctx, host, podName, remoteName, params, authToken)
}
