// Code generated by MockGen. DO NOT EDIT.
// Source: load.go
//
// Generated by this command:
//
//	mockgen -source=load.go -destination=mock_load_client_test.go -package=snapshot_test
//

// Package snapshot_test is a generated GoMock package.
package snapshot_test

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLocalLoadClient is a mock of LocalLoadClient interface.
type MockLocalLoadClient struct {
	ctrl     *gomock.Controller
	recorder *MockLocalLoadClientMockRecorder
	isgomock struct{}
}

// MockLocalLoadClientMockRecorder is the mock recorder for MockLocalLoadClient.
type MockLocalLoadClientMockRecorder struct {
	mock *MockLocalLoadClient
}

// NewMockLocalLoadClient creates a new mock instance.
func NewMockLocalLoadClient(ctrl *gomock.Controller) *MockLocalLoadClient {
	mock := &MockLocalLoadClient{ctrl: ctrl}
	mock.recorder = &MockLocalLoadClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalLoadClient) EXPECT() *MockLocalLoadClientMockRecorder {
	return m.recorder
}

// ImportState mocks base method.
func (m *MockLocalLoadClient) ImportState(ctx context.Context, host string, src io.Reader, strategy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportState", ctx, host, src, strategy)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportState indicates an expected call of ImportState.
func (mr *MockLocalLoadClientMockRecorder) ImportState(ctx, host, src, strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportState", reflect.TypeOf((*MockLocalLoadClient)(nil).ImportState), ctx, host, src, strategy)
}

// ResetState mocks base method.
func (m *MockLocalLoadClient) ResetState(ctx context.Context, host string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetState", ctx, host)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetState indicates an expected call of ResetState.
func (mr *MockLocalLoadClientMockRecorder) ResetState(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetState", reflect.TypeOf((*MockLocalLoadClient)(nil).ResetState), ctx, host)
}

// MockPodLoader is a mock of PodLoader interface.
type MockPodLoader struct {
	ctrl     *gomock.Controller
	recorder *MockPodLoaderMockRecorder
	isgomock struct{}
}

// MockPodLoaderMockRecorder is the mock recorder for MockPodLoader.
type MockPodLoaderMockRecorder struct {
	mock *MockPodLoader
}

// NewMockPodLoader creates a new mock instance.
func NewMockPodLoader(ctrl *gomock.Controller) *MockPodLoader {
	mock := &MockPodLoader{ctrl: ctrl}
	mock.recorder = &MockPodLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodLoader) EXPECT() *MockPodLoaderMockRecorder {
	return m.recorder
}

// LoadPodSnapshot mocks base method.
func (m *MockPodLoader) LoadPodSnapshot(ctx context.Context, host, podName, authToken, strategy string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPodSnapshot", ctx, host, podName, authToken, strategy)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPodSnapshot indicates an expected call of LoadPodSnapshot.
func (mr *MockPodLoaderMockRecorder) LoadPodSnapshot(ctx, host, podName, authToken, strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPodSnapshot", reflect.TypeOf((*MockPodLoader)(nil).LoadPodSnapshot), ctx, host, podName, authToken, strategy)
}
