// Code generated by MockGen. DO NOT EDIT.
// Source: remove.go
//
// Generated by this command:
//
//	mockgen -source=remove.go -destination=mock_remove_client_test.go -package=snapshot_test
//

// Package snapshot_test is a generated GoMock package.
package snapshot_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPodRemover is a mock of PodRemover interface.
type MockPodRemover struct {
	ctrl     *gomock.Controller
	recorder *MockPodRemoverMockRecorder
	isgomock struct{}
}

// MockPodRemoverMockRecorder is the mock recorder for MockPodRemover.
type MockPodRemoverMockRecorder struct {
	mock *MockPodRemover
}

// NewMockPodRemover creates a new mock instance.
func NewMockPodRemover(ctrl *gomock.Controller) *MockPodRemover {
	mock := &MockPodRemover{ctrl: ctrl}
	mock.recorder = &MockPodRemoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodRemover) EXPECT() *MockPodRemoverMockRecorder {
	return m.recorder
}

// RemovePodSnapshot mocks base method.
func (m *MockPodRemover) RemovePodSnapshot(ctx context.Context, host, podName, authToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePodSnapshot", ctx, host, podName, authToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePodSnapshot indicates an expected call of RemovePodSnapshot.
func (mr *MockPodRemoverMockRecorder) RemovePodSnapshot(ctx, host, podName, authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePodSnapshot", reflect.TypeOf((*MockPodRemover)(nil).RemovePodSnapshot), ctx, host, podName, authToken)
}
