// Code generated by MockGen. DO NOT EDIT.
// Source: internal/runtime/runtime.go
//
// Generated by this command:
//
//	mockgen -source=internal/runtime/runtime.go -destination=internal/runtime/mock_runtime.go -package=runtime
//

// Package runtime is a generated GoMock package.
package runtime

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	output "github.com/localstack/lstk/internal/output"
	gomock "go.uber.org/mock/gomock"
)

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
	isgomock struct{}
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// FindRunningByImage mocks base method.
func (m *MockRuntime) FindRunningByImage(ctx context.Context, imageRepo string, containerPort string) (*RunningContainer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRunningByImage", ctx, imageRepo, containerPort)
	ret0, _ := ret[0].(*RunningContainer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRunningByImage indicates an expected call of FindRunningByImage.
func (mr *MockRuntimeMockRecorder) FindRunningByImage(ctx, imageRepo, containerPort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRunningByImage", reflect.TypeOf((*MockRuntime)(nil).FindRunningByImage), ctx, imageRepo, containerPort)
}

// ContainerStartedAt mocks base method.
func (m *MockRuntime) ContainerStartedAt(ctx context.Context, containerName string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerStartedAt", ctx, containerName)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerStartedAt indicates an expected call of ContainerStartedAt.
func (mr *MockRuntimeMockRecorder) ContainerStartedAt(ctx, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerStartedAt", reflect.TypeOf((*MockRuntime)(nil).ContainerStartedAt), ctx, containerName)
}

// EmitUnhealthyError mocks base method.
func (m *MockRuntime) EmitUnhealthyError(sink output.Sink, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitUnhealthyError", sink, err)
}

// EmitUnhealthyError indicates an expected call of EmitUnhealthyError.
func (mr *MockRuntimeMockRecorder) EmitUnhealthyError(sink, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitUnhealthyError", reflect.TypeOf((*MockRuntime)(nil).EmitUnhealthyError), sink, err)
}

// GetBoundPort mocks base method.
func (m *MockRuntime) GetBoundPort(ctx context.Context, containerName string, containerPort string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoundPort", ctx, containerName, containerPort)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoundPort indicates an expected call of GetBoundPort.
func (mr *MockRuntimeMockRecorder) GetBoundPort(ctx, containerName, containerPort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoundPort", reflect.TypeOf((*MockRuntime)(nil).GetBoundPort), ctx, containerName, containerPort)
}

// GetImageVersion mocks base method.
func (m *MockRuntime) GetImageVersion(ctx context.Context, imageName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageVersion", ctx, imageName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageVersion indicates an expected call of GetImageVersion.
func (mr *MockRuntimeMockRecorder) GetImageVersion(ctx, imageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageVersion", reflect.TypeOf((*MockRuntime)(nil).GetImageVersion), ctx, imageName)
}

// IsHealthy mocks base method.
func (m *MockRuntime) IsHealthy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockRuntimeMockRecorder) IsHealthy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockRuntime)(nil).IsHealthy), ctx)
}

// IsRunning mocks base method.
func (m *MockRuntime) IsRunning(ctx context.Context, containerID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning", ctx, containerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockRuntimeMockRecorder) IsRunning(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockRuntime)(nil).IsRunning), ctx, containerID)
}

// Logs mocks base method.
func (m *MockRuntime) Logs(ctx context.Context, containerID string, tail int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, containerID, tail)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logs indicates an expected call of Logs.
func (mr *MockRuntimeMockRecorder) Logs(ctx, containerID, tail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockRuntime)(nil).Logs), ctx, containerID, tail)
}

// PullImage mocks base method.
func (m *MockRuntime) PullImage(ctx context.Context, image string, progress chan<- PullProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullImage", ctx, image, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// PullImage indicates an expected call of PullImage.
func (mr *MockRuntimeMockRecorder) PullImage(ctx, image, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullImage", reflect.TypeOf((*MockRuntime)(nil).PullImage), ctx, image, progress)
}

// Remove mocks base method.
func (m *MockRuntime) Remove(ctx context.Context, containerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, containerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRuntimeMockRecorder) Remove(ctx, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRuntime)(nil).Remove), ctx, containerName)
}

// SocketPath mocks base method.
func (m *MockRuntime) SocketPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SocketPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// SocketPath indicates an expected call of SocketPath.
func (mr *MockRuntimeMockRecorder) SocketPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SocketPath", reflect.TypeOf((*MockRuntime)(nil).SocketPath))
}

// Start mocks base method.
func (m *MockRuntime) Start(ctx context.Context, config ContainerConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, config)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockRuntimeMockRecorder) Start(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRuntime)(nil).Start), ctx, config)
}

// Stop mocks base method.
func (m *MockRuntime) Stop(ctx context.Context, containerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, containerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRuntimeMockRecorder) Stop(ctx, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRuntime)(nil).Stop), ctx, containerName)
}

// StreamLogs mocks base method.
func (m *MockRuntime) StreamLogs(ctx context.Context, containerID string, out io.Writer, follow bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamLogs", ctx, containerID, out, follow)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamLogs indicates an expected call of StreamLogs.
func (mr *MockRuntimeMockRecorder) StreamLogs(ctx, containerID, out, follow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamLogs", reflect.TypeOf((*MockRuntime)(nil).StreamLogs), ctx, containerID, out, follow)
}
