// Code generated by MockGen. DO NOT EDIT.
// Source: reset.go
//
// Generated by this command:
//
//	mockgen -source=reset.go -destination=mock_state_resetter_test.go -package=reset_test
//

// Package reset_test is a generated GoMock package.
package reset_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStateResetter is a mock of StateResetter interface.
type MockStateResetter struct {
	ctrl     *gomock.Controller
	recorder *MockStateResetterMockRecorder
	isgomock struct{}
}

// MockStateResetterMockRecorder is the mock recorder for MockStateResetter.
type MockStateResetterMockRecorder struct {
	mock *MockStateResetter
}

// NewMockStateResetter creates a new mock instance.
func NewMockStateResetter(ctrl *gomock.Controller) *MockStateResetter {
	mock := &MockStateResetter{ctrl: ctrl}
	mock.recorder = &MockStateResetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateResetter) EXPECT() *MockStateResetterMockRecorder {
	return m.recorder
}

// ResetState mocks base method.
func (m *MockStateResetter) ResetState(ctx context.Context, host string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetState", ctx, host)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetState indicates an expected call of ResetState.
func (mr *MockStateResetterMockRecorder) ResetState(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetState", reflect.TypeOf((*MockStateResetter)(nil).ResetState), ctx, host)
}
