// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_platform_api.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlatformAPI is a mock of PlatformAPI interface.
type MockPlatformAPI struct {
	ctrl     *gomock.Controller
	recorder *MockPlatformAPIMockRecorder
	isgomock struct{}
}

// MockPlatformAPIMockRecorder is the mock recorder for MockPlatformAPI.
type MockPlatformAPIMockRecorder struct {
	mock *MockPlatformAPI
}

// NewMockPlatformAPI creates a new mock instance.
func NewMockPlatformAPI(ctrl *gomock.Controller) *MockPlatformAPI {
	mock := &MockPlatformAPI{ctrl: ctrl}
	mock.recorder = &MockPlatformAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlatformAPI) EXPECT() *MockPlatformAPIMockRecorder {
	return m.recorder
}

// CheckAuthRequestConfirmed mocks base method.
func (m *MockPlatformAPI) CheckAuthRequestConfirmed(ctx context.Context, id, exchangeToken string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAuthRequestConfirmed", ctx, id, exchangeToken)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAuthRequestConfirmed indicates an expected call of CheckAuthRequestConfirmed.
func (mr *MockPlatformAPIMockRecorder) CheckAuthRequestConfirmed(ctx, id, exchangeToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAuthRequestConfirmed", reflect.TypeOf((*MockPlatformAPI)(nil).CheckAuthRequestConfirmed), ctx, id, exchangeToken)
}

// CreateAuthRequest mocks base method.
func (m *MockPlatformAPI) CreateAuthRequest(ctx context.Context) (*AuthRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthRequest", ctx)
	ret0, _ := ret[0].(*AuthRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthRequest indicates an expected call of CreateAuthRequest.
func (mr *MockPlatformAPIMockRecorder) CreateAuthRequest(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthRequest", reflect.TypeOf((*MockPlatformAPI)(nil).CreateAuthRequest), ctx)
}

// ExchangeAuthRequest mocks base method.
func (m *MockPlatformAPI) ExchangeAuthRequest(ctx context.Context, id, exchangeToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeAuthRequest", ctx, id, exchangeToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeAuthRequest indicates an expected call of ExchangeAuthRequest.
func (mr *MockPlatformAPIMockRecorder) ExchangeAuthRequest(ctx, id, exchangeToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeAuthRequest", reflect.TypeOf((*MockPlatformAPI)(nil).ExchangeAuthRequest), ctx, id, exchangeToken)
}

// GetLatestCatalogVersion mocks base method.
func (m *MockPlatformAPI) GetLatestCatalogVersion(ctx context.Context, emulatorType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestCatalogVersion", ctx, emulatorType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestCatalogVersion indicates an expected call of GetLatestCatalogVersion.
func (mr *MockPlatformAPIMockRecorder) GetLatestCatalogVersion(ctx, emulatorType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestCatalogVersion", reflect.TypeOf((*MockPlatformAPI)(nil).GetLatestCatalogVersion), ctx, emulatorType)
}

// GetLicense mocks base method.
func (m *MockPlatformAPI) GetLicense(ctx context.Context, req *LicenseRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLicense", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetLicense indicates an expected call of GetLicense.
func (mr *MockPlatformAPIMockRecorder) GetLicense(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLicense", reflect.TypeOf((*MockPlatformAPI)(nil).GetLicense), ctx, req)
}

// GetLicenseToken mocks base method.
func (m *MockPlatformAPI) GetLicenseToken(ctx context.Context, bearerToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLicenseToken", ctx, bearerToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLicenseToken indicates an expected call of GetLicenseToken.
func (mr *MockPlatformAPIMockRecorder) GetLicenseToken(ctx, bearerToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLicenseToken", reflect.TypeOf((*MockPlatformAPI)(nil).GetLicenseToken), ctx, bearerToken)
}
