package cli

import "github.com/localstack/lstk/internal/log"

// defaultOverrideFileName is the name of the generated provider-override file
// when LSTK_TF_OVERRIDE_FILE_NAME is not set. Terraform merges any file named
// *_override.tf over the user's own configuration, so this requires no edits
// to the user's files.
const defaultOverrideFileName = "localstack_providers_override.tf"

// overrideFileMarker is written as the first line of every override file lstk
// generates, as an informational header for anyone who finds a copy left
// behind (e.g. if lstk was hard-killed before cleanup ran).
const overrideFileMarker = "# Generated by lstk - do not edit. This file is removed automatically."

// awsProviderType is the namespace/type of the AWS provider as it appears in
// `<tool> providers schema -json` keys. The full key is prefixed with the
// reporting registry host, which differs by tool — Terraform uses
// registry.terraform.io, OpenTofu uses registry.opentofu.org, and private
// mirrors use other hosts — so we match on this stable suffix rather than a
// fixed host.
const awsProviderType = "hashicorp/aws"

// unproxiedCommands are the Terraform subcommands that lstk always runs
// directly, without generating an override file or resolving the LocalStack
// endpoint. The set is fixed and is intentionally not configurable via an
// environment variable.
//
// fmt/validate/version are pure offline utilities that never touch provider
// endpoints or backend access. init is NOT in this set: it is conditionally
// proxied (see RequiresEmulator) — it passes through when no S3 backend is
// declared (to bootstrap the provider, whose schema the override's endpoint
// keys are discovered from), but redirects and provisions the backend when an
// S3 backend is present.
var unproxiedCommands = map[string]bool{
	"fmt":      true,
	"validate": true,
	"version":  true,
}

// IsUnproxied reports whether the terraform invocation described by args is one
// of the unconditionally unproxied subcommands (fmt/validate/version). The
// subcommand is the first argument that is not a flag (terraform's global
// options, e.g. -chdir, precede the subcommand).
func IsUnproxied(args []string) bool {
	return unproxiedCommands[subcommand(args)]
}

// RequiresEmulator reports whether the invocation needs a running LocalStack
// emulator (and thus the endpoint-resolution path in cmd). fmt/validate/version
// never do. init needs one only when the working directory declares an S3
// backend (it must then redirect the backend and provision its resources);
// without a backend, init passes through to bootstrap the provider. Every other
// subcommand (plan/apply/destroy/…) is proxied and needs the emulator.
func RequiresEmulator(args []string, workdir string, logger log.Logger) bool {
	if IsUnproxied(args) {
		return false
	}
	if subcommand(args) == "init" {
		return HasS3Backend(workdir, logger)
	}
	return true
}

// subcommand returns the first non-flag token in args, or "" if there is none.
func subcommand(args []string) string {
	for _, a := range args {
		if len(a) > 0 && a[0] != '-' {
			return a
		}
	}
	return ""
}
