package cli

// defaultOverrideFileName is the name of the generated provider-override file
// when LSTK_TF_OVERRIDE_FILE_NAME is not set. Terraform merges any file named
// *_override.tf over the user's own configuration, so this requires no edits
// to the user's files.
const defaultOverrideFileName = "localstack_providers_override.tf"

// overrideFileMarker is written as the first line of every override file lstk
// generates, as an informational header for anyone who finds a copy left
// behind (e.g. if lstk was hard-killed before cleanup ran).
const overrideFileMarker = "# Generated by lstk - do not edit. This file is removed automatically."

// awsProviderType is the namespace/type of the AWS provider as it appears in
// `<tool> providers schema -json` keys. The full key is prefixed with the
// reporting registry host, which differs by tool — Terraform uses
// registry.terraform.io, OpenTofu uses registry.opentofu.org, and private
// mirrors use other hosts — so we match on this stable suffix rather than a
// fixed host.
const awsProviderType = "hashicorp/aws"

// unproxiedCommands are the Terraform subcommands that lstk runs directly,
// without generating an override file or resolving the LocalStack endpoint. The
// set is fixed and is intentionally not configurable via an environment
// variable.
//
// fmt/validate/version are pure offline utilities that never touch provider
// endpoints. init is included because it installs the provider: the override's
// endpoint keys are discovered from the provider schema, which does not exist
// until init has run, so init must pass through to bootstrap the provider for
// subsequent plan/apply. init does not call AWS service endpoints (S3-backend
// support is out of scope), so it needs no override.
var unproxiedCommands = map[string]bool{
	"fmt":      true,
	"validate": true,
	"version":  true,
	"init":     true,
}

// IsUnproxied reports whether the terraform invocation described by args is one
// of the unproxied subcommands. The subcommand is the first argument that is
// not a flag (terraform's global options, e.g. -chdir, precede the subcommand).
func IsUnproxied(args []string) bool {
	return unproxiedCommands[subcommand(args)]
}

// subcommand returns the first non-flag token in args, or "" if there is none.
func subcommand(args []string) string {
	for _, a := range args {
		if len(a) > 0 && a[0] != '-' {
			return a
		}
	}
	return ""
}
