// Package proc runs wrapped external tools (aws, terraform, cdk, sam, az, and
// extensions) so that termination signals reach the child gracefully instead of
// hard-killing it.
package proc

import (
	"os"
	"os/exec"
	"os/signal"
	"syscall"

	"github.com/localstack/lstk/internal/terminal"
)

// forwardedSignals are relayed to the wrapped child so it can shut down
// gracefully (e.g. terraform releasing its state lock) rather than being killed
// abruptly.
var forwardedSignals = []os.Signal{os.Interrupt, syscall.SIGTERM}

// shouldForward decides whether a received signal is relayed to the child.
// SIGTERM is never generated by a terminal, so it is always forwarded — without
// that, `kill <lstk-pid>` or `timeout 30 lstk terraform apply` would never reach
// the wrapped tool. SIGINT is terminal-generated (Ctrl-C) and already delivered
// to the child via the controlling terminal's foreground process group, so
// forwarding it while attached to a terminal would double-signal the tool — and
// a second, near-simultaneous SIGINT makes tools like terraform abort
// immediately instead of cleaning up.
func shouldForward(sig os.Signal, attachedToTerminal bool) bool {
	return sig != os.Interrupt || !attachedToTerminal
}

// attachedToTerminal reports whether any of lstk's std streams is a terminal —
// i.e. whether a terminal's foreground process group will deliver Ctrl-C to the
// wrapped child directly. Checking stdin alone is not enough: with stdin
// redirected (`yes | lstk terraform apply`) lstk still runs in the terminal's
// foreground process group.
func attachedToTerminal() bool {
	return terminal.IsTerminal(os.Stdin) || terminal.IsTerminal(os.Stdout) || terminal.IsTerminal(os.Stderr)
}

// Run starts cmd, waits for it to exit, and returns the same error cmd.Run
// would. It ensures SIGINT/SIGTERM reach the wrapped tool exactly once so it can
// clean up instead of being SIGKILLed the instant lstk's context is cancelled.
//
// When cmd was created with exec.CommandContext, its default Cancel hard-kills
// the child (SIGKILL) as soon as the context is done — which is exactly what
// happens on Ctrl-C, since lstk cancels its root context on SIGINT/SIGTERM. Run
// disarms that: a cancelled context no longer kills the child, so the tool
// terminates from the signal it receives and lstk waits for it to finish its own
// shutdown. Returning os.ErrProcessDone from Cancel both suppresses the kill and
// avoids injecting context.Canceled into the wait result, so the tool's real
// exit code is preserved.
//
// Received signals are relayed per shouldForward: SIGTERM always, SIGINT only
// when lstk is not attached to a terminal (an attached terminal already
// delivers Ctrl-C to the child via the foreground process group). npm/launcher.js
// forwards unconditionally instead — safe there because its child is lstk,
// which tolerates duplicate signals; wrapped tools like terraform do not.
func Run(cmd *exec.Cmd) error {
	// Disarm exec.CommandContext's SIGKILL-on-cancel (no-op for a plain
	// exec.Command, whose Cancel is nil).
	if cmd.Cancel != nil {
		cmd.Cancel = func() error { return os.ErrProcessDone }
	}

	attached := attachedToTerminal()

	// Register before Start so a signal landing during startup is queued and
	// relayed once the child is running, not silently swallowed by lstk's own
	// root handler.
	sigCh := make(chan os.Signal, len(forwardedSignals))
	signal.Notify(sigCh, forwardedSignals...)
	defer signal.Stop(sigCh)

	if err := cmd.Start(); err != nil {
		return err
	}

	done := make(chan struct{})
	defer close(done)
	go func() {
		for {
			select {
			case sig := <-sigCh:
				if shouldForward(sig, attached) {
					_ = cmd.Process.Signal(sig)
				}
			case <-done:
				return
			}
		}
	}()

	return cmd.Wait()
}
