// Code generated by MockGen. DO NOT EDIT.
// Source: login.go
//
// Generated by this command:
//
//	mockgen -source=login.go -destination=mock_login_test.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginProvider is a mock of LoginProvider interface.
type MockLoginProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLoginProviderMockRecorder
	isgomock struct{}
}

// MockLoginProviderMockRecorder is the mock recorder for MockLoginProvider.
type MockLoginProviderMockRecorder struct {
	mock *MockLoginProvider
}

// NewMockLoginProvider creates a new mock instance.
func NewMockLoginProvider(ctrl *gomock.Controller) *MockLoginProvider {
	mock := &MockLoginProvider{ctrl: ctrl}
	mock.recorder = &MockLoginProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginProvider) EXPECT() *MockLoginProviderMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockLoginProvider) Login(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockLoginProviderMockRecorder) Login(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockLoginProvider)(nil).Login), ctx)
}
