// Code generated by MockGen. DO NOT EDIT.
// Source: keyring.go
//
// Generated by this command:
//
//	mockgen -source=keyring.go -destination=mock_keyring_test.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKeyring is a mock of Keyring interface.
type MockKeyring struct {
	ctrl     *gomock.Controller
	recorder *MockKeyringMockRecorder
	isgomock struct{}
}

// MockKeyringMockRecorder is the mock recorder for MockKeyring.
type MockKeyringMockRecorder struct {
	mock *MockKeyring
}

// NewMockKeyring creates a new mock instance.
func NewMockKeyring(ctrl *gomock.Controller) *MockKeyring {
	mock := &MockKeyring{ctrl: ctrl}
	mock.recorder = &MockKeyringMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyring) EXPECT() *MockKeyringMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockKeyring) Get(service, user string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", service, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKeyringMockRecorder) Get(service, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKeyring)(nil).Get), service, user)
}

// Set mocks base method.
func (m *MockKeyring) Set(service, user, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", service, user, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockKeyringMockRecorder) Set(service, user, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockKeyring)(nil).Set), service, user, password)
}
