// Code generated by MockGen. DO NOT EDIT.
// Source: token_storage.go
//
// Generated by this command:
//
//	mockgen -source=token_storage.go -destination=mock_token_storage.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthTokenStorage is a mock of AuthTokenStorage interface.
type MockAuthTokenStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAuthTokenStorageMockRecorder
	isgomock struct{}
}

// MockAuthTokenStorageMockRecorder is the mock recorder for MockAuthTokenStorage.
type MockAuthTokenStorageMockRecorder struct {
	mock *MockAuthTokenStorage
}

// NewMockAuthTokenStorage creates a new mock instance.
func NewMockAuthTokenStorage(ctrl *gomock.Controller) *MockAuthTokenStorage {
	mock := &MockAuthTokenStorage{ctrl: ctrl}
	mock.recorder = &MockAuthTokenStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthTokenStorage) EXPECT() *MockAuthTokenStorageMockRecorder {
	return m.recorder
}

// DeleteAuthToken mocks base method.
func (m *MockAuthTokenStorage) DeleteAuthToken() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuthToken")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuthToken indicates an expected call of DeleteAuthToken.
func (mr *MockAuthTokenStorageMockRecorder) DeleteAuthToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthToken", reflect.TypeOf((*MockAuthTokenStorage)(nil).DeleteAuthToken))
}

// GetAuthToken mocks base method.
func (m *MockAuthTokenStorage) GetAuthToken() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthToken indicates an expected call of GetAuthToken.
func (mr *MockAuthTokenStorageMockRecorder) GetAuthToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthToken", reflect.TypeOf((*MockAuthTokenStorage)(nil).GetAuthToken))
}

// SetAuthToken mocks base method.
func (m *MockAuthTokenStorage) SetAuthToken(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAuthToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAuthToken indicates an expected call of SetAuthToken.
func (mr *MockAuthTokenStorageMockRecorder) SetAuthToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthToken", reflect.TypeOf((*MockAuthTokenStorage)(nil).SetAuthToken), token)
}

// Mockkeyringer is a mock of keyringer interface.
type Mockkeyringer struct {
	ctrl     *gomock.Controller
	recorder *MockkeyringerMockRecorder
	isgomock struct{}
}

// MockkeyringerMockRecorder is the mock recorder for Mockkeyringer.
type MockkeyringerMockRecorder struct {
	mock *Mockkeyringer
}

// NewMockkeyringer creates a new mock instance.
func NewMockkeyringer(ctrl *gomock.Controller) *Mockkeyringer {
	mock := &Mockkeyringer{ctrl: ctrl}
	mock.recorder = &MockkeyringerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockkeyringer) EXPECT() *MockkeyringerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *Mockkeyringer) Delete(service, user string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", service, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockkeyringerMockRecorder) Delete(service, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockkeyringer)(nil).Delete), service, user)
}

// Get mocks base method.
func (m *Mockkeyringer) Get(service, user string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", service, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockkeyringerMockRecorder) Get(service, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockkeyringer)(nil).Get), service, user)
}

// Set mocks base method.
func (m *Mockkeyringer) Set(service, user, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", service, user, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockkeyringerMockRecorder) Set(service, user, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*Mockkeyringer)(nil).Set), service, user, password)
}
