package integration_test

import (
	"testing"

	"github.com/localstack/lstk/internal/snap"
	"github.com/stretchr/testify/require"
)

// TestInvalidUsageExitsNonZero guards against regressions of DEVX-941, where
// lstk exited 0 even when a command failed. It covers two failure classes that
// must surface a non-zero exit code: an unknown flag, and an unknown subcommand
// of a parent command that only groups subcommands (config/setup/volume/
// snapshot, plus Cobra's autogenerated completion). The latter used to exit 0
// because Cobra prints help and returns nil for an unrecognized subcommand of a
// non-runnable parent.
func TestInvalidUsageExitsNonZero(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		args []string
	}{
		{"unknown flag on start", []string{"start", "--bogus-flag-xyz"}},
		{"unknown flag on root", []string{"--bogus-flag-xyz"}},
		{"unknown command", []string{"bogus-command"}},
		{"unknown config subcommand", []string{"config", "bogus"}},
		{"removed config profile subcommand", []string{"config", "profile"}},
		{"unknown setup subcommand", []string{"setup", "bogus"}},
		{"unknown volume subcommand", []string{"volume", "bogus"}},
		{"unknown snapshot subcommand", []string{"snapshot", "bogus"}},
		{"unknown completion shell", []string{"completion", "bogus"}},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			e := testEnvWithHome(t.TempDir(), "")
			_, stderr, err := runLstk(t, testContext(t), t.TempDir(), e, tc.args...)
			require.Error(t, err, "expected %v to fail", tc.args)
			requireExitCode(t, 1, err)
			snap.Match(t, sanitizeOutput(stderr))
		})
	}
}

// TestBareParentCommandExitsZero confirms that invoking a subcommand-grouping
// parent with no subcommand still prints help and exits 0 — the fix for
// DEVX-941 must reject unknown subcommands without breaking bare invocations.
func TestBareParentCommandExitsZero(t *testing.T) {
	t.Parallel()

	for _, parent := range []string{"config", "setup", "volume", "snapshot", "completion"} {
		parent := parent
		t.Run(parent, func(t *testing.T) {
			t.Parallel()
			e := testEnvWithHome(t.TempDir(), "")
			stdout, _, err := runLstk(t, testContext(t), t.TempDir(), e, parent)
			require.NoError(t, err)
			requireExitCode(t, 0, err)
			snap.Match(t, sanitizeOutput(stdout))
		})
	}
}
