package integration_test

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/localstack/lstk/internal/must"
	"github.com/localstack/lstk/internal/snap"
	"github.com/localstack/lstk/test/integration/env"
	"github.com/moby/moby/client"
)

func TestStatusCommandFailsWhenNotRunning(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	analyticsSrv, events := mockAnalyticsServer(t)
	stdout, _, err := runLstk(t, testContext(t), "", env.With(env.AnalyticsEndpoint, analyticsSrv.URL), "status")
	must.Error(t, err, "expected lstk status to fail when emulator not running")
	requireExitCode(t, 1, err)
	snap.Match(t, sanitizeOutput(stdout))
	assertCommandTelemetry(t, events, "status", 1)
}

func TestStatusCommandShowsResourcesWhenRunning(t *testing.T) {
	requireDocker(t)
	_ = env.Require(t, env.AuthToken)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)

	mockServer := createMockLicenseServer(true)
	defer mockServer.Close()

	_, stderr, err := runLstk(t, ctx, "", env.With(env.APIEndpoint, mockServer.URL), "start")
	must.NoError(t, err, "lstk start failed: %s", stderr)

	awsCfg, err := awsconfig.LoadDefaultConfig(ctx,
		awsconfig.WithRegion("us-east-1"),
		awsconfig.WithCredentialsProvider(credentials.NewStaticCredentialsProvider("test", "test", "")),
		awsconfig.WithBaseEndpoint("http://localhost:4566"),
	)
	must.NoError(t, err)

	s3Client := s3.NewFromConfig(awsCfg, func(o *s3.Options) { o.UsePathStyle = true })
	_, err = s3Client.CreateBucket(ctx, &s3.CreateBucketInput{Bucket: aws.String("my-test-bucket")})
	must.NoError(t, err, "failed to create S3 bucket")

	sqsClient := sqs.NewFromConfig(awsCfg)
	_, err = sqsClient.CreateQueue(ctx, &sqs.CreateQueueInput{QueueName: aws.String("my-test-queue")})
	must.NoError(t, err, "failed to create SQS queue")

	analyticsSrv, events := mockAnalyticsServer(t)
	stdout, stderr, err := runLstk(t, ctx, "", env.With(env.AnalyticsEndpoint, analyticsSrv.URL), "status")
	must.NoError(t, err, "lstk status failed: %s", stderr)
	requireExitCode(t, 0, err)
	// Not a snapshot: this test needs a real auth token and a live emulator,
	// so a committed snapshot could not be regenerated by most contributors
	// (and the resources table layout varies with the emulator image).
	must.Contains(t, stdout, "running")
	must.Contains(t, stdout, "SERVICE")
	must.Contains(t, stdout, "RESOURCE")
	must.Contains(t, stdout, "S3")
	must.Contains(t, stdout, "my-test-bucket")
	must.Contains(t, stdout, "SQS")
	must.Contains(t, stdout, "my-test-queue")
	assertCommandTelemetry(t, events, "status", 0)
}

func TestStatusCommandWorksWithNonDefaultPort(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)

	// The mock server is assigned a random free port (guaranteed not to conflict).
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_localstack/health":
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintln(w, `{"version": "4.14.1", "services": {}}`)
		case "/_localstack/resources":
			w.Header().Set("Content-Type", "application/x-ndjson")
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	// Extract the port so we can bind it to the container.
	_, mockPort, err := net.SplitHostPort(server.Listener.Addr().String())
	must.NoError(t, err)

	// Simulates starting LocalStack on a non-default host port.
	startTestContainer(t, ctx, mockPort)

	// Write a config with the default port 4566
	// Simulates the user changing the config port after starting the container
	configContent := "[[containers]]\ntype = \"aws\"\ntag = \"latest\"\nport = \"4566\"\n"
	configFile := filepath.Join(t.TempDir(), "config.toml")
	must.NoError(t, os.WriteFile(configFile, []byte(configContent), 0644))

	stdout, stderr, err := runLstk(t, ctx, "", testEnvWithHome(t.TempDir(), ""), "--config", configFile, "status")
	must.NoError(t, err, "lstk status failed: %s", stderr)
	must.Contains(t, stdout, "4.14.1")
}

func TestStatusCommandWorksWithExternalContainer(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)

	const fakeImage = "localstack/localstack-pro:test-fake"
	_, err := dockerClient.ImageTag(ctx, client.ImageTagOptions{Source: testImage, Target: fakeImage})
	must.NoError(t, err)
	t.Cleanup(func() {
		_, _ = dockerClient.ImageRemove(context.Background(), fakeImage, client.ImageRemoveOptions{})
	})

	startExternalContainer(t, ctx, fakeImage, "localstack-external", "4566")

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_localstack/health":
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintln(w, `{"version": "3.5.0", "services": {}}`)
		case "/_localstack/resources":
			w.Header().Set("Content-Type", "application/x-ndjson")
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	stdout, stderr, err := runLstk(t, ctx, "", env.With(env.LocalStackHost, lsHost(server)), "status")
	must.NoError(t, err, "lstk status should work with external container: %s", stderr)
	requireExitCode(t, 0, err)
	must.Contains(t, stdout, "3.5.0")
}

func TestStatusCommandForSnowflakeShowsNoResources(t *testing.T) {
	requireDocker(t)
	cleanupSnowflake()
	t.Cleanup(cleanupSnowflake)

	ctx := testContext(t)
	startTestSnowflakeContainer(t, ctx)

	stdout, stderr, err := runLstk(t, ctx, "", testEnvWithHome(t.TempDir(), ""), "--config", writeSnowflakeConfig(t, "4566"), "status")
	must.NoError(t, err, "lstk status failed for snowflake: %s", stderr)
	requireExitCode(t, 0, err)

	must.Contains(t, stdout, "Snowflake")
	must.Contains(t, stdout, "running")
	must.Contains(t, stdout, "snowflake.localhost.localstack.cloud:4566",
		"snowflake status should display the snowflake-routed host clients use to connect")
	// Snowflake does not expose AWS resources — no resource table or empty-state message.
	must.NotContains(t, stdout, "SERVICE")
	must.NotContains(t, stdout, "No resources deployed")
}

func TestStatusCommandForSnowflakeShowsVersion(t *testing.T) {
	requireDocker(t)
	_ = env.Require(t, env.AuthToken)

	cleanup()
	cleanupSnowflake()
	t.Cleanup(cleanup)
	t.Cleanup(cleanupSnowflake)

	mockServer := createMockLicenseServer(true)
	defer mockServer.Close()

	const hostPort = "4566"
	configFile := writeSnowflakeConfig(t, hostPort)

	ctx := testContext(t)
	_, stderr, err := runLstk(t, ctx, "", env.With(env.APIEndpoint, mockServer.URL), "--config", configFile, "start")
	must.NoError(t, err, "lstk start failed: %s", stderr)
	requireExitCode(t, 0, err)

	expectedVersion := fetchSnowflakeVersion(t, hostPort)

	stdout, stderr, err := runLstk(t, ctx, "", testEnvWithHome(t.TempDir(), ""), "--config", configFile, "status")
	must.NoError(t, err, "lstk status failed: %s", stderr)
	requireExitCode(t, 0, err)

	must.Contains(t, stdout, "• Version: "+expectedVersion,
		"snowflake status should display the version reported by /_localstack/health")
}

func TestStatusCommandShowsNoResourcesWhenEmpty(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)
	startTestContainer(t, ctx)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_localstack/health":
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintln(w, `{"version": "4.14.1", "services": {}}`)
		case "/_localstack/resources":
			w.Header().Set("Content-Type", "application/x-ndjson")
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	stdout, stderr, err := runLstk(t, ctx, "", env.With(env.LocalStackHost, lsHost(server)), "status")
	must.NoError(t, err, "lstk status failed: %s", stderr)
	requireExitCode(t, 0, err)
	must.Contains(t, stdout, "No resources deployed")
}

func fetchSnowflakeVersion(t *testing.T, hostPort string) string {
	t.Helper()
	resp, err := http.Get(fmt.Sprintf("http://localhost:%s/_localstack/health", hostPort))
	must.NoError(t, err, "failed to fetch snowflake health")
	t.Cleanup(func() { _ = resp.Body.Close() })
	body, err := io.ReadAll(resp.Body)
	must.NoError(t, err, "failed to read snowflake health body")
	var h struct {
		Version string `json:"version"`
	}
	must.NoError(t, json.Unmarshal(body, &h), "failed to decode snowflake health: %s", body)
	must.NotEmpty(t, h.Version, "snowflake health response missing version field")
	return h.Version
}
