package integration_test

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/localstack/lstk/internal/snap"
	"github.com/localstack/lstk/test/integration/env"
	"github.com/moby/moby/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestStatusCommandFailsWhenNotRunning(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	analyticsSrv, events := mockAnalyticsServer(t)
	stdout, _, err := runLstk(t, testContext(t), "", env.With(env.AnalyticsEndpoint, analyticsSrv.URL), "status")
	require.Error(t, err, "expected lstk status to fail when emulator not running")
	requireExitCode(t, 1, err)
	snap.Match(t, sanitizeOutput(stdout))
	assertCommandTelemetry(t, events, "status", 1)
}

func TestStatusCommandShowsResourcesWhenRunning(t *testing.T) {
	requireDocker(t)
	_ = env.Require(t, env.AuthToken)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)

	mockServer := createMockLicenseServer(true)
	defer mockServer.Close()

	_, stderr, err := runLstk(t, ctx, "", env.With(env.APIEndpoint, mockServer.URL), "start")
	require.NoError(t, err, "lstk start failed: %s", stderr)

	awsCfg, err := awsconfig.LoadDefaultConfig(ctx,
		awsconfig.WithRegion("us-east-1"),
		awsconfig.WithCredentialsProvider(credentials.NewStaticCredentialsProvider("test", "test", "")),
		awsconfig.WithBaseEndpoint("http://localhost:4566"),
	)
	require.NoError(t, err)

	s3Client := s3.NewFromConfig(awsCfg, func(o *s3.Options) { o.UsePathStyle = true })
	_, err = s3Client.CreateBucket(ctx, &s3.CreateBucketInput{Bucket: aws.String("my-test-bucket")})
	require.NoError(t, err, "failed to create S3 bucket")

	sqsClient := sqs.NewFromConfig(awsCfg)
	_, err = sqsClient.CreateQueue(ctx, &sqs.CreateQueueInput{QueueName: aws.String("my-test-queue")})
	require.NoError(t, err, "failed to create SQS queue")

	analyticsSrv, events := mockAnalyticsServer(t)
	stdout, stderr, err := runLstk(t, ctx, "", env.With(env.AnalyticsEndpoint, analyticsSrv.URL), "status")
	require.NoError(t, err, "lstk status failed: %s", stderr)
	requireExitCode(t, 0, err)
	// Not a snapshot: this test needs a real auth token and a live emulator,
	// so a committed snapshot could not be regenerated by most contributors
	// (and the resources table layout varies with the emulator image).
	assert.Contains(t, stdout, "running")
	assert.Contains(t, stdout, "SERVICE")
	assert.Contains(t, stdout, "RESOURCE")
	assert.Contains(t, stdout, "S3")
	assert.Contains(t, stdout, "my-test-bucket")
	assert.Contains(t, stdout, "SQS")
	assert.Contains(t, stdout, "my-test-queue")
	assertCommandTelemetry(t, events, "status", 0)
}

func TestStatusCommandWorksWithNonDefaultPort(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)

	// The mock server is assigned a random free port (guaranteed not to conflict).
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_localstack/health":
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintln(w, `{"version": "4.14.1", "services": {}}`)
		case "/_localstack/resources":
			w.Header().Set("Content-Type", "application/x-ndjson")
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	// Extract the port so we can bind it to the container.
	_, mockPort, err := net.SplitHostPort(server.Listener.Addr().String())
	require.NoError(t, err)

	// Simulates starting LocalStack on a non-default host port.
	startTestContainer(t, ctx, mockPort)

	// Write a config with the default port 4566
	// Simulates the user changing the config port after starting the container
	configContent := "[[containers]]\ntype = \"aws\"\ntag = \"latest\"\nport = \"4566\"\n"
	configFile := filepath.Join(t.TempDir(), "config.toml")
	require.NoError(t, os.WriteFile(configFile, []byte(configContent), 0644))

	stdout, stderr, err := runLstk(t, ctx, "", testEnvWithHome(t.TempDir(), ""), "--config", configFile, "status")
	require.NoError(t, err, "lstk status failed: %s", stderr)
	assert.Contains(t, stdout, "4.14.1")
}

func TestStatusCommandWorksWithExternalContainer(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)

	const fakeImage = "localstack/localstack-pro:test-fake"
	_, err := dockerClient.ImageTag(ctx, client.ImageTagOptions{Source: testImage, Target: fakeImage})
	require.NoError(t, err)
	t.Cleanup(func() {
		_, _ = dockerClient.ImageRemove(context.Background(), fakeImage, client.ImageRemoveOptions{})
	})

	startExternalContainer(t, ctx, fakeImage, "localstack-external", "4566")

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_localstack/health":
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintln(w, `{"version": "3.5.0", "services": {}}`)
		case "/_localstack/resources":
			w.Header().Set("Content-Type", "application/x-ndjson")
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	stdout, stderr, err := runLstk(t, ctx, "", env.With(env.LocalStackHost, lsHost(server)), "status")
	require.NoError(t, err, "lstk status should work with external container: %s", stderr)
	requireExitCode(t, 0, err)
	assert.Contains(t, stdout, "3.5.0")
}

func TestStatusCommandForSnowflakeShowsNoResources(t *testing.T) {
	requireDocker(t)
	cleanupSnowflake()
	t.Cleanup(cleanupSnowflake)

	ctx := testContext(t)
	startTestSnowflakeContainer(t, ctx)

	stdout, stderr, err := runLstk(t, ctx, "", testEnvWithHome(t.TempDir(), ""), "--config", writeSnowflakeConfig(t, "4566"), "status")
	require.NoError(t, err, "lstk status failed for snowflake: %s", stderr)
	requireExitCode(t, 0, err)

	assert.Contains(t, stdout, "Snowflake")
	assert.Contains(t, stdout, "running")
	assert.Contains(t, stdout, "snowflake.localhost.localstack.cloud:4566",
		"snowflake status should display the snowflake-routed host clients use to connect")
	// Snowflake does not expose AWS resources — no resource table or empty-state message.
	assert.NotContains(t, stdout, "SERVICE")
	assert.NotContains(t, stdout, "No resources deployed")
}

func TestStatusCommandForSnowflakeShowsVersion(t *testing.T) {
	requireDocker(t)
	_ = env.Require(t, env.AuthToken)

	cleanup()
	cleanupSnowflake()
	t.Cleanup(cleanup)
	t.Cleanup(cleanupSnowflake)

	mockServer := createMockLicenseServer(true)
	defer mockServer.Close()

	const hostPort = "4566"
	configFile := writeSnowflakeConfig(t, hostPort)

	ctx := testContext(t)
	_, stderr, err := runLstk(t, ctx, "", env.With(env.APIEndpoint, mockServer.URL), "--config", configFile, "start")
	require.NoError(t, err, "lstk start failed: %s", stderr)
	requireExitCode(t, 0, err)

	expectedVersion := fetchSnowflakeVersion(t, hostPort)

	stdout, stderr, err := runLstk(t, ctx, "", testEnvWithHome(t.TempDir(), ""), "--config", configFile, "status")
	require.NoError(t, err, "lstk status failed: %s", stderr)
	requireExitCode(t, 0, err)

	assert.Contains(t, stdout, "• Version: "+expectedVersion,
		"snowflake status should display the version reported by /_localstack/health")
}

func TestStatusCommandShowsNoResourcesWhenEmpty(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)
	startTestContainer(t, ctx)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_localstack/health":
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintln(w, `{"version": "4.14.1", "services": {}}`)
		case "/_localstack/resources":
			w.Header().Set("Content-Type", "application/x-ndjson")
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	stdout, stderr, err := runLstk(t, ctx, "", env.With(env.LocalStackHost, lsHost(server)), "status")
	require.NoError(t, err, "lstk status failed: %s", stderr)
	requireExitCode(t, 0, err)
	assert.Contains(t, stdout, "No resources deployed")
}

func TestStatusCommandJSONRunning(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)
	startTestContainer(t, ctx)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_localstack/health":
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintln(w, `{"version": "4.14.1", "services": {}}`)
		case "/_localstack/resources":
			w.Header().Set("Content-Type", "application/x-ndjson")
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	stdout, stderr, err := runLstk(t, ctx, "", env.With(env.LocalStackHost, lsHost(server)), "status", "--json")
	require.NoError(t, err, "lstk status --json failed: %s", stderr)
	requireExitCode(t, 0, err)

	envelope := decodeEnvelope(t, stdout)
	assert.Equal(t, "ok", envelope.Status)
	assert.Equal(t, "status", envelope.Command)
	assert.Nil(t, envelope.Error)

	var data struct {
		Emulators []struct {
			Type            string `json:"type"`
			Running         bool   `json:"running"`
			Health          string `json:"health"`
			Name            string `json:"name"`
			Version         string `json:"version"`
			Host            string `json:"host"`
			ResourceSummary *struct {
				Resources int `json:"resources"`
			} `json:"resourceSummary"`
		} `json:"emulators"`
	}
	require.NoError(t, json.Unmarshal(envelope.Data, &data))
	require.Len(t, data.Emulators, 1)
	e := data.Emulators[0]
	assert.Equal(t, "aws", e.Type)
	assert.True(t, e.Running)
	assert.Equal(t, "healthy", e.Health)
	assert.Equal(t, containerName, e.Name)
	assert.Equal(t, "4.14.1", e.Version)
	assert.NotEmpty(t, e.Host)
	assert.Nil(t, e.ResourceSummary, "resources should be excluded by default")
}

func TestStatusCommandJSONNotRunning(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	stdout, _, err := runLstk(t, testContext(t), "", testEnvWithHome(t.TempDir(), ""), "status", "--json")
	requireExitCode(t, 1, err)

	envelope := decodeEnvelope(t, stdout)
	assert.Equal(t, "error", envelope.Status)
	require.NotNil(t, envelope.Error)
	assert.Equal(t, "EMULATOR_NOT_RUNNING", envelope.Error.Code)
	assert.Equal(t, "EMULATOR", envelope.Error.Category)
}

func TestStatusCommandJSONResourcesFlag(t *testing.T) {
	requireDocker(t)
	cleanup()
	t.Cleanup(cleanup)

	ctx := testContext(t)
	startTestContainer(t, ctx)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_localstack/health":
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintln(w, `{"version": "4.14.1", "services": {}}`)
		case "/_localstack/resources":
			w.Header().Set("Content-Type", "application/x-ndjson")
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	stdout, stderr, err := runLstk(t, ctx, "", env.With(env.LocalStackHost, lsHost(server)), "status", "--json", "--resources")
	require.NoError(t, err, "lstk status --json --resources failed: %s", stderr)
	requireExitCode(t, 0, err)

	envelope := decodeEnvelope(t, stdout)
	var data struct {
		Emulators []struct {
			ResourceSummary *struct {
				Resources int `json:"resources"`
				Services  int `json:"services"`
			} `json:"resourceSummary"`
			Resources []json.RawMessage `json:"resources"`
		} `json:"emulators"`
	}
	require.NoError(t, json.Unmarshal(envelope.Data, &data))
	require.Len(t, data.Emulators, 1)
	require.NotNil(t, data.Emulators[0].ResourceSummary, "--resources should include a resourceSummary")
	assert.Equal(t, 0, data.Emulators[0].ResourceSummary.Resources)
	assert.Empty(t, data.Emulators[0].Resources)
}

func TestStatusCommandJSONExternalEndpoint(t *testing.T) {
	t.Parallel()
	srv := awsHealthServer(t)
	defer srv.Close()

	e := env.With(env.DisableEvents, "1").WithHome(t.TempDir())
	e = append(e, unreachableDockerHost)

	stdout, stderr, err := runLstk(t, testContext(t), t.TempDir(), e, "--endpoint-url", srv.URL, "status", "--json")
	require.NoError(t, err, "lstk status --json --endpoint-url failed: %s", stderr)
	requireExitCode(t, 0, err)

	envelope := decodeEnvelope(t, stdout)
	assert.Equal(t, "ok", envelope.Status)

	var data struct {
		Emulators []map[string]json.RawMessage `json:"emulators"`
	}
	require.NoError(t, json.Unmarshal(envelope.Data, &data))
	require.Len(t, data.Emulators, 1)
	emu := data.Emulators[0]
	assert.JSONEq(t, `"aws"`, string(emu["type"]))
	assert.JSONEq(t, `true`, string(emu["running"]))
	assert.JSONEq(t, `"healthy"`, string(emu["health"]))
	assert.JSONEq(t, `"3.0.2"`, string(emu["version"]))
	assert.NotContains(t, emu, "name", "an external target has no container name")
	assert.NotContains(t, emu, "uptimeSeconds", "an external target has no known uptime")
	assert.NotContains(t, emu, "persistence", "an external target has no known persistence setting")
}

func TestStatusCommandJSONExternalEndpointResources(t *testing.T) {
	t.Parallel()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_localstack/health":
			w.Header().Set("Content-Type", "application/json")
			_, _ = fmt.Fprintln(w, `{"version": "3.0.2", "services": {"s3": "available"}}`)
		case "/_localstack/resources":
			w.Header().Set("Content-Type", "application/x-ndjson")
			_, _ = fmt.Fprintln(w, `{"AWS::S3::Bucket": [{"region_name": "us-east-1", "account_id": "000000000000", "id": "my-test-bucket"}]}`)
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer srv.Close()

	e := env.With(env.DisableEvents, "1").WithHome(t.TempDir())
	e = append(e, unreachableDockerHost)

	stdout, stderr, err := runLstk(t, testContext(t), t.TempDir(), e, "--endpoint-url", srv.URL, "status", "--json", "--resources")
	require.NoError(t, err, "lstk status --json --resources --endpoint-url failed: %s", stderr)
	requireExitCode(t, 0, err)

	envelope := decodeEnvelope(t, stdout)
	var data struct {
		Emulators []struct {
			ResourceSummary *struct {
				Resources int `json:"resources"`
			} `json:"resourceSummary"`
			Resources []struct {
				Name string `json:"name"`
			} `json:"resources"`
		} `json:"emulators"`
	}
	require.NoError(t, json.Unmarshal(envelope.Data, &data))
	require.Len(t, data.Emulators, 1)
	require.NotNil(t, data.Emulators[0].ResourceSummary)
	assert.Equal(t, 1, data.Emulators[0].ResourceSummary.Resources)
	require.Len(t, data.Emulators[0].Resources, 1)
	assert.Equal(t, "my-test-bucket", data.Emulators[0].Resources[0].Name)
}

func fetchSnowflakeVersion(t *testing.T, hostPort string) string {
	t.Helper()
	resp, err := http.Get(fmt.Sprintf("http://localhost:%s/_localstack/health", hostPort))
	require.NoError(t, err, "failed to fetch snowflake health")
	t.Cleanup(func() { _ = resp.Body.Close() })
	body, err := io.ReadAll(resp.Body)
	require.NoError(t, err, "failed to read snowflake health body")
	var h struct {
		Version string `json:"version"`
	}
	require.NoError(t, json.Unmarshal(body, &h), "failed to decode snowflake health: %s", body)
	require.NotEmpty(t, h.Version, "snowflake health response missing version field")
	return h.Version
}
