name: Linear Release

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read

jobs:
  linear-release:
    name: Create Linear release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Create Linear release
        uses: linear/linear-release-action@53ad0f863963e7f8e270fba18426bbb55ef55384 # v0.17.2
        with:
          access_key: ${{ secrets.LINEAR_ACCESS_KEY }}
          name: ${{ github.ref_name }}
          version: ${{ github.ref_name }}
