name: Linear Release

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read

jobs:
  linear-release:
    name: Create Linear release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create Linear release
        uses: linear/linear-release-action@v0
        with:
          access_key: ${{ secrets.LINEAR_ACCESS_KEY }}
